print("""
burlywood            : #deb887
lightsteelblue       : #b0c4de
lightcyan            : #e0ffff
darkgreen            : #006400
dimgray              : #696969
gainsboro            : #dcdcdc
lightgoldenrodyellow : #fafad2
brown                : #a52a2a
mediumvioletred      : #c71585
lawngreen            : #7cfc00
turquoise            : #40e0d0
darkred              : #8b0000
aqua                 : #00ffff
steelblue            : #4682b4
grey                 : #808080
lavender             : #e6e6fa
plum                 : #dda0dd
darkturquoise        : #00ced1
ghostwhite           : #f8f8ff
blue                 : #0000ff
darkorange           : #ff8c00
mediumorchid         : #ba55d3
salmon               : #fa8072
rebeccapurple        : #663399
greenyellow          : #adff2f
mediumseagreen       : #3cb371
darkmagenta          : #8b008b
lightgrey            : #d3d3d3
palegoldenrod        : #eee8aa
lime                 : #00ff00
blanchedalmond       : #ffebcd
antiquewhite         : #faebd7
cornsilk             : #fff8dc
darkgray             : #a9a9a9
mediumslateblue      : #7b68ee
floralwhite          : #fffaf0
khaki                : #f0e68c
saddlebrown          : #8b4513
cornflowerblue       : #6495ed
oldlace              : #fdf5e6
lavenderblush        : #fff0f5
firebrick            : #b22222
cyan                 : #00ffff
violet               : #ee82ee
coral                : #ff7f50
palevioletred        : #db7093
lightcoral           : #f08080
purple               : #800080
tomato               : #ff6347
darksalmon           : #e9967a
olive                : #808000
goldenrod            : #daa520
midnightblue         : #191970
mintcream            : #f5fffa
honeydew             : #f0fff0
limegreen            : #32cd32
gray                 : #808080
silver               : #c0c0c0
chartreuse           : #7fff00
aliceblue            : #f0f8ff
gold                 : #ffd700
lemonchiffon         : #fffacd
wheat                : #f5deb3
hotpink              : #ff69b4
mediumblue           : #0000cd
darkviolet           : #9400d3
black                : #000000
navajowhite          : #ffdead
ivory                : #fffff0
chocolate            : #d2691e
lightyellow          : #ffffe0
lightsalmon          : #ffa07a
olivedrab            : #6b8e23
darkslategray        : #2f4f4f
lightslategrey       : #778899
slategrey            : #708090
mediumaquamarine     : #66cdaa
thistle              : #d8bfd8
lightseagreen        : #20b2aa
indianred            : #cd5c5c
darkblue             : #00008b
white                : #ffffff
linen                : #faf0e6
powderblue           : #b0e0e6
darkolivegreen       : #556b2f
magenta              : #ff00ff
indigo               : #4b0082
lightskyblue         : #87cefa
maroon               : #800000
mediumpurple         : #9370db
whitesmoke           : #f5f5f5
rosybrown            : #bc8f8f
lightgray            : #d3d3d3
lightgreen           : #90ee90
darkcyan             : #008b8b
red                  : (255, 0, 0)
papayawhip           : #ffefd5
royalblue            : #4169e1
seagreen             : #2e8b57
orangered            : #ff4500
forestgreen          : #228b22
cadetblue            : #5f9ea0
darkkhaki            : #bdb76b
orchid               : #da70d6
beige                : #f5f5dc
darkseagreen         : #8fbc8f
darkgrey             : #a9a9a9
yellowgreen          : #9acd32
slategray            : #708090
pink                 : #ffc0cb
springgreen          : #00ff7f
mediumturquoise      : #48d1cc
seashell             : #fff5ee
yellow               : #ffff00
blueviolet           : #8a2be2
mediumspringgreen    : #00fa9a
lightblue            : #add8e6
deeppink             : #ff1493
snow                 : #fffafa
skyblue              : #87ceeb
peachpuff            : #ffdab9
tan                  : #d2b48c
darkslategrey        : #2f4f4f
darkgoldenrod        : #b8860b
navy                 : #000080
darkorchid           : #9932cc
slateblue            : #6a5acd
azure                : #f0ffff
green                : #008000
lightpink            : #ffb6c1
sienna               : #a0522d
orange               : #ffa500
deepskyblue          : #00bfff
dimgrey              : #696969
fuchsia              : #ff00ff
mistyrose            : #ffe4e1
bisque               : #ffe4c4
crimson              : #dc143c
darkslateblue        : #483d8b
teal                 : #008080
paleturquoise        : #afeeee
aquamarine           : #7fffd4
sandybrown           : #f4a460
palegreen            : #98fb98
dodgerblue           : #1e90ff
moccasin             : #ffe4b5
lightslategray       : #778899
peru                 : #cd853f
""")
